let places :string[]=[ ' Jerusalem ',' Ramallah ',' Gaza ',' Bethlehem ',' Janin ',' Nablus ',' Hebron ',' Rafah '];
console.log('\nOrignal :' + places);
console.log('\nCopy :' + [...places].sort());
console.log('\nOrignal :' + places);
console.log('\nCopy :' + [...places].sort().reverse());
console.log('\nOrignal :' + places);
console.log('\nOrignal :' + places.reverse());
console.log('\nOrignal :' + places.reverse());
console.log('\nOrignal :' + places.sort());
console.log('\nOrignal :' + places.sort().reverse());